version: '3.5'
services:
  spark-master:
    container_name: spark-master
    image: bde2020/spark-master:2.4.5-hadoop2.7
    volumes:
    - /src/files/data:/src/data
    ports:
      - "10001:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      
  spark-worker-1:
    container_name: spark-worker-1
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    volumes: 
    - /src/files/data:/src/data
    depends_on:
      - spark-master
    ports:
      - "10002:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    ports:
      - "10003:1433"
    environment:
      SA_PASSWORD: "VeryComplicatedPassword2020"
      ACCEPT_EULA: "Y"

  lenses-dev:
    container_name: kafka
    image: landoop/kafka-lenses-dev:latest
    ports:
      - 10004:3030
    environment:
      - EULA=${LENSES_LICENSE}
   
  postgres:
    container_name: postgres
    image: postgres:9.6
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    logging:
        options:
            max-size: 10m
            max-file: "3"
            
  webserver:
    container_name: airflow  
    image: kwdocker2020/airflow-spark:v1
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=n
        - EXECUTOR=Local
        - VIRTUAL_HOST=airflow
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        
    logging:
        options:
            max-size: 10m
            max-file: "3"
    volumes:
        - /src/files/data:/src/data
        - /src/files/spark:/usr/local/airflow/spark
        - /src/files/airflow/dags:/usr/local/airflow/dags
        - /src/files/airflow/plugins:/usr/local/airflow/plugins
    ports:
        - "10005:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3   